### ISSUE TITLE
version attribute uninitialized

### ISSUE THREAD

**Issue by majd1239** [brunneis/easysolc#1]
Upon usage:
solc = Solc()
solc.compile(..)

This throws an error as line 109 tries to access self.version for logging but version attribute is only set upon calling the method `get_version`.

Easy solution to initialize version in `__init__`

**Comment by brunneis** [comment]
Thank you @majd1239 for noticing it. I removed the initialization of the `version` attribute so the `get_contract_instance` method can be used even if the compiler is not installed. Accesing the value through the `get_version` method instead of directly read the `version` attribute solves the issue.
